### ISSUE TITLE
Crashes when attempting to install from file etc

### ISSUE THREAD

**Issue by JetLynx** [flipperdevices/qFlipper#127] opened 2022-09-28 03:57 UTC
First and foremost, thank you for your interest in making qFlipper better by reporting bugs!

**in Windows 10, qFlipper crashes when I try to install firmware from file, Backup, or Restore. Attempting to factory reset using Erase function also stays on "Performing Factory Reset" screen and never fails nor succeeds**
What were you trying to do? Install custom firmware, specifically RogueMaster. At this point I can't do any of the above functions.

**To Reproduce**
1. Run qFlipper, either normally or as Administrator
2. Click on install from file, Backup, or Restore
3. See qFlipper crash immediately

**Expected behavior**
Firmware flashing process to run and complete. Or any of the above functions to run without crashing.

**Actual behavior**
qFlipper crashes without any error messages or dialog windows.

**Additional troubleshooting**
1. Does the issue persist if you try multiple times? Yes
2. Does reconnecting/rebooting Flipper solve it? No
3. Does re-installing solve the issue? No
4. Does running as Administrator solve it? No
5. Does restarting the computer solve it? No
6. Does formatting the SD Card and performing the factory update and database install solve it? No

**The report *must* also include at least one of the following:**
1. A **FULL LOG** of this application run. (see below).
2. A screenshot of the application window (if it is a graphical issue).

**Additional context**
Running Erase results in the program staying on the progress screen, Reinstall seems to work.

[qFlipper-20220927-204941.txt](https://github.com/flipperdevices/qFlipper/files/9661353/qFlipper-20220927-204941.txt)

**Comment by lastCoyotes** [comment] 2022-09-28 07:10
Quickfix until a solution patches the logic, but for anyone else who has this issue it's due to qFlipper opening up the File Browser to a location that doesn't exist if it saved that location as the last location used.

https://github.com/flipperdevices/qFlipper/issues/124#issuecomment-1260480394

**Comment by JetLynx** [comment] 2022-09-28 07:17
> Quickfix until a solution patches the logic, but for anyone else who has this issue it's due to qFlipper opening up the File Browser to a location that doesn't exist if it saved that location as the last location used.
> 
> [#124 (comment)](https://github.com/flipperdevices/qFlipper/issues/124#issuecomment-1260480394)

I recreated the directory that's listed at the end of the log and now all issues are resolved.

**Comment by gsurkov** [comment] 2022-09-28 14:04
Duplicate of #124. The fix will be released as soon as we fix our build system.

**Closed as completed by gsurkov** 2022-09-28 14:04 UTC
Labels: bug
