### ISSUE TITLE
Provide a source code archive with third-party dependencies included

### ISSUE THREAD

**Issue by invakid404** [flipperdevices/qFlipper#190] opened 2023-07-12 22:28 UTC
Basically the title. As a Linux package maintainer for a source-based distro, my life would be much easier if there was a source code archive for releases that includes the necessary third-party dependencies to build qFlipper so that they don't have to be installed system-wide/fetched separately.

**Comment by gsurkov** [comment] 2023-11-01 15:46
Duplicate of #57.
TL;DR: Github does that and there is no way to change it.

A proper way for a source-based distro to get sources would be checking out a particular tag via git. See [ArchLinux AUR PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qflipper-git) file for approximate example.

**Closed as completed by gsurkov** 2023-11-01 15:46 UTC
