### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by SpinchGang** [flipperdevices/qFlipper#208] opened 2023-12-09 20:27 UTC
I would love to see something similar to the apps section of the mobile app come to qflipper. I understand that lab.flipper.net can be used for this, however, I think the process of updating and downloading apps in one desktop application would provide for a more seamless experience for using the flipper

**Comment by mhalano** [comment] 2023-12-15 22:06
@SpinchGang I think you are completely right. Maybe you just should put a more descriptive title in the issue. :)

**Comment by gsurkov** [comment] 2024-02-27 13:19
Duplicate of #204.
Will be implemented sometime in the future.

**Closed as completed by gsurkov** 2024-02-27 13:19 UTC
