### ISSUE TITLE
Unable to drag and drop files and folders into file manager in qFlipper 1.2.0

### ISSUE THREAD

**Issue by jmgelman** [flipperdevices/qFlipper#123] opened 2022-09-21 21:00 UTC
**Describe the bug**
Drag and drop files and folders into the File Manager in qFlipper 1.2.0

**To Reproduce**
1. Open qFlipper.
2. Navigate to File Manager.
3. Open Windows Explorer.
4. Attempt to drag and drop a file or folder from Windows Explorer.

**Expected behavior**
Dropping file or folder should upload the file to the Flipper SD card.

**Actual behavior**
Cursor changes to "not-allowed" and cannot drop file or folder.

**Additional troubleshooting**
Issue did not appear in previous version of qFlipper.

**Screenshot**
![2022-09-21 16_58_53-Road_Arm_(UK)](https://user-images.githubusercontent.com/4539090/191609405-9f4e2ef9-ffd3-4116-bf27-9eb427ccf970.png)

**Comment by gsurkov** [comment] 2022-09-22 09:31
~~I was not able to reproduce it on Windows 10.~~

**UPD:**
It is most likely due to qFlipper being run with Administrator privileges (it may happen if you launched it by checking "Run qFlipper now" in the installer.) Try closing it and then run normally. If that isn't helping then see the spoiler below.

<details>
<summary>If that's not the case...</summary>
Which exact version of Windows 10 are you using? (you can find it out right at the beginning of qFlipper's log.)
Does the path to the file you are attempting to drag contain any peculiar symbols?
Does the problem persist if you restart qFlipper? If you restart Windows? 
There allegedly was a case of "not allowed" cursor if the user tried to drag a file into the root directory (which is not allowed), and then attempted to drag it into another folder. Is it what you did? 
Does your system have multiple displays? If so, does moving qFlipper onto the other display do anything?
</details>

**Comment by jmgelman** [comment] 2022-09-22 11:05
@gsurkov Thank you, that appears to be the cause. I initially chose "Run qFlipper now" after the installer completed. 

I did close and relaunch the app, but relaunched it as an administrator also, thinking maybe I needed admin privileges now for drag-and-drop to work. So both times I was running it as an administrator. When I launch it as a normal user, per your suggestion, drag-and-drop works again as expected.

I was not aware that drag-and-drop is disabled when the app is run as an administrator. Is that by design?

**Comment by gsurkov** [comment] 2022-09-22 13:11
Windows disables drag-and-drop from regular programs to privileged ones as a security measure (only learned this today), so qFlipper has nothing to do with it.

Closing this issue, but will keep in mind that the installer needs be fixed so that it would launch qFlipper without admin privileges.

**Closed as completed by gsurkov** 2022-09-22 13:11 UTC
Labels: bug
